#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

CURRENT_BORDER='1'
CURRENT_GAP='8'
CURRENT_SRATIO='1.4'

BLUE="#00acc1"
CYAN="#7dcfff"
BACKGROUND="#f9f5d7"
MAGENTA="#d3869b"
GREEN="#43a047"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$CYAN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


# WALLPAPER
feh --bg-fill ~/Wallpapers/a.jpg

# POLYBAR
~/.config/polybar/launch.sh

# PICOM
picom &

# Fix pipe
xmodmap -e "keycode 94 = bar backslash"

# Fix brace
xmodmap -e "keycode 51 = braceright"

# Fix "X" cursor
xsetroot -cursor_name left_ptr
