#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1

bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart up applications 
~/.config/polybar/launch.sh --forest &
picom & 
feh --bg-fill ~/Pictures/Wallpapers/images/japan.png &
xrdb merge ~/.Xresources &
sxhkd 
mpd &
